apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-python-calculator
  template:
    metadata:
      labels:
        app: sample-python-calculator
    spec:
      containers:
        - name: sample-python-calculator
          image: ghcr.io/amitweb2012/flask-calculator:21841417233-e241087460b524ab7d8892882993e3edbf9c1748
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
